services:
  rdpserver:
    network_mode: host
    build: ./esp32-rdp
    image: esp32-rdp-server:latest
    container_name: esp32-rdp
    restart: unless-stopped
    environment:
      TARGET_URL: "http://172.16.0.252:8123/dashboard-mobile/0"
      VIEWPORT_W: 480
      VIEWPORT_H: 480
      TILE: 64
      SCAN_INTERVAL_MS: 200
      FULLFRAME_EVERY: 50
      WS_PORT: 8081
      DEBUG_PORT: 9222
      HEALTH_PORT: 18080
      USER_DATA_DIR: /pw-data
    volumes:
      - /opt/volumes/esp32-rdp/pw-data:/pw-data
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:18080 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    # devices:
    #   - "/dev/dri:/dev/dri"
  rdpdevtools:
    image: alpine/socat
    network_mode: "service:rdpserver"
    command:
      - "TCP-LISTEN:19222,fork,reuseaddr,keepalive"
      - "TCP:127.0.0.1:9222"
    restart: unless-stopped
    